<div class="col-sm-12 col-md-8">
    <div class="card">
        <div class="card-header bg-dark text-light">
            Nouveau Potain
        </div>
        <div class="card-body">
            <form action="addArticle.php" method="POST">
                <blockquote class="blockquote mb-0">
                    <div class="form-group">
                        <label for="Categorie">Categorie</label>
                        <select class="form-control <?php if(isset($error['Categorie'])):?>alert-danger<?php endif?>" id="Categorie" name="Categorie" placeholder="Categorie" value="<?=$Categorie?>">
                        <option selected="selected"></option>
                        <?php foreach ($categories as $categorie) : ?>
                            <option><?= $categorie['categorie']; ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                    <label for="inputtitle" class="col-sm-6 col-form-label">title</label>
                    <input class="form-control <?php if(isset($error['title'])):?>alert-danger<?php endif?>" type="text" placeholder="titre" name="title" value="<?=$title?>">

                    <label for="inputsubtitle" class="col-sm-6 col-form-label">Subtitle</label>
                    <input class="form-control <?php if(isset($error['Subtitle'])):?>alert-danger<?php endif?>" type="text" placeholder="Sous-Title" name="subtitle" value="<?=$subtitle?>">

                    <label for="inputimage" class="col-sm-6 col-form-label">Image</label>
                    <input class="form-control <?php if(isset($error['image'])):?>alert-danger<?php endif?>" type="text" placeholder="image" name="image" value="<?=$image?>">

                    <label for="inputstatus" class="col-sm-6 col-form-label">status</label>
                    <input class="form-control <?php if(isset($error['status'])):?>alert-danger<?php endif?>" type="text" placeholder="status" name="status" value="<?=$status?>">

                    <label for="inputpublished_date" class="col-sm-6 col-form-label">published_date</label>
                    <textarea class="form-control <?php if(isset($error['published_date'])):?>alert-danger<?php endif?>" rows="3" id="published_date" placeholder="date de publication" name="published_date" ><?=$published_date?></textarea>

                    <input type="submit" class="btn btn-primary" value="<?=$submit?>">
                </blockquote>
            </form>
        </div>
    </div>
</div>