<div class="col-sm-12 col-md-8">
    <div class="card">
        <div class="card-header bg-dark text-light">
            Nouveau Padawon
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <label for="inputUsername" class="col-sm-6 col-form-label">Username</label>
                <input class="form-control" type="text" placeholder="Username">

                <label for="inputEmail" class="col-sm-6 col-form-label">email</label>
                <input class="form-control" type="text" placeholder="email">

                <label for="inputFirstname" class="col-sm-6 col-form-label">firstname</label>
                <input class="form-control" type="text" placeholder="firstname">

                <label for="inputlastname" class="col-sm-6 col-form-label">lastname</label>
                <input class="form-control" type="text" placeholder="lastname">

                <label for="inputBio" class="col-sm-6 col-form-label">bio</label>
                <textarea class="form-control" rows="3" id="bio"></textarea>

                <label for="inputPass" class="col-sm-6 col-form-label">mot de passe</label>
                <input class="form-control" type="text" placeholder="mot de passe">

                <label for="inputPass2" class="col-sm-6 col-form-label">confirmation mot de passe</label>
                <input class="form-control" type="text" placeholder="confirmation mot de passe">

                <div class="form-group">
                    <label for="exampleFormControlSelect1">Role</label>
                    <select class="form-control" id="exampleFormControlSelect1">
                        <option>ROLE_ADMIN</option>
                        <option>ROLE_AUTHOR</option>
                    </select>
                </div>
                    <a href="#" class="btn btn-primary">Enregistrer</a>
            </blockquote>
        </div>
    </div>
</div>