

<div class="col-sm-12 col-md-8">
    
    <table class="table table-dark">
        <thead>
            <tr>
            <th scope="col">Id</th>
            <th scope="col">Nom</th>
            <th scope="col">Ordre</th>
            <th scope="col">Parent</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categories as $categorie) : ?>
                <tr>
                    <td><a href="categorieId=<?= $categorie['id'];?>"><?= $categorie['id']; ?></a></td>
                    <td><?= $categorie['libele']; ?></td>
                    <td><?= $categorie['order']; ?></td>
                    <td><?= $categorie['categories_id']; ?></td>
                    <td scope="col">
                        <a href="#"><i class="fas fa-edit"></i></a>
                        <a href="categorieDel.php?id=<?= $categorie['id'];?>"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            <?php endforeach ?>

        </tbody>
    </table>
</div>