<p class="text-right">Bienvenue, <?php (isset($_SESSION['user']))?$_SESSION['user']['username']:''; ?></p>
<h1>Accueil</h1>
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <div class="card">
                <div class="card-header bg-dark text-light">
                    Visualisation rapide
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                    <p>Pour voir tout de suite votre site</p>
                    <a href="#" class="btn btn-primary btn-block">Afficher votre site</a>
                    </blockquote>
                </div>
            </div>
            <div class="card mt-4">
                <div class="card-header bg-dark text-light">
                    Actions rapides
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0 d-flex flex-column">
                        <a href="#" class="card-link"><i class="far fa-newspaper"></i> Ajouter un article</a>
                        <a href="#" class="card-link"><i class="far fa-file"></i> Ajouter une page</a>
                        <a href="addUser.php" class="card-link"><i class="fas fa-user-alt"></i> Ajouter un utilisateur</a>
                    </blockquote>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-8">
                <div class="card">
                        <div class="card-header bg-dark text-light">
                            Article rapide
                        </div>
                        <div class="card-body">
                            <blockquote class="blockquote mb-0">
                                <label for="inputTitle" class="col-sm-6 col-form-label">Titre de l'article</label>
                                <input class="form-control" type="text" placeholder="titre">
                                <label for="inputDetail" class="col-sm-6 col-form-label">Texte de l'article</label>
                                <textarea class="form-control" rows="3" id="detail"></textarea>
                                <div class="form-check">
                                    <div class="custom-control custom-radio custom-control-inline">
                                        <input type="radio" class="custom-control-input" id="customControlValidation2" name="radio-stacked" required>
                                        <label class="custom-control-label" for="customControlValidation2">Publier</label>
                                    </div>
                                    <div class="custom-control custom-radio mb-3 custom-control-inline">
                                        <input type="radio" class="custom-control-input" id="customControlValidation3" name="radio-stacked" required>
                                        <label class="custom-control-label" for="customControlValidation3">Brouillon</label>
                                        <div class="invalid-feedback">More example invalid feedback text</div>
                                    </div>
                                </div>
                                <div>
                                    <a href="#" class="btn btn-primary">Enregistrer</a>
                                </div>
                            </blockquote>
                        </div>
                    </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-sm-12 col-md-7">
            <div class="card">
                <div class="card-header bg-dark text-light">
                        Liste des derniers articles
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <h6>Article 1</h6>  
                        <p>début du texte de l'article (...)</p>
                        <footer class="blockquote-footer">Auteur :<cite title="Source Title">Christophe</cite></footer>
                    </li>
                    <li class="list-group-item">
                        <h6>Article 2</h6>  
                        <p>début du texte de l'article (...)</p>
                        <footer class="blockquote-footer">Auteur :<cite title="Source Title">Christophe</cite></footer>
                    </li>
                    <li class="list-group-item">
                        <h6>Article 3</h6>  
                        <p>début du texte de l'article (...)</p>
                        <footer class="blockquote-footer">Auteur :<cite title="Source Title">Christophe</cite></footer>
                    </li>
                    <li class="list-group-item">
                        <h6>Article 4</h6>  
                        <p>début du texte de l'article (...)</p>
                        <footer class="blockquote-footer">Auteur :<cite title="Source Title">Christophe</cite></footer>
                    </li>
                </ul>
            </div>
            <a href="#" class="card-link">Voir tout les articles</a>
        </div>
        <div class="col-sm-12 col-md-5">
            <div class="card">
                <div class="card-header bg-dark text-light">
                    Liste des derniers commentaires
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer class="blockquote-footer">DE:<cite title="Source Title">Christophe</cite></footer>
                    </li>
                    <li class="list-group-item">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer class="blockquote-footer">DE:<cite title="Source Title">Christophe</cite></footer>
                    </li>
                    <li class="list-group-item">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer class="blockquote-footer">DE:<cite title="Source Title">Christophe</cite></footer>
                    </li>
                    <li class="list-group-item">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer class="blockquote-footer">DE:<cite title="Source Title">Christophe</cite></footer>
                    </li>
                </ul>
            </div> 
            <a href="#" class="card-link">Voir tout les commentaires</a>    
        </div>
    </div>