<div class="col-sm-12 col-md-8">
    <div class="card">
        <div class="card-header bg-dark text-light">
            Article rapide
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <label for="inputTitle" class="col-sm-6 col-form-label">Titre de l'article</label>
                <input class="form-control" type="text" placeholder="titre">
                <label for="inputDetail" class="col-sm-6 col-form-label">Texte de l'article</label>
                <textarea class="form-control" rows="3" id="detail"></textarea>
                <div class="form-check">
                    <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" class="custom-control-input" id="customControlValidation2" name="radio-stacked" required>
                        <label class="custom-control-label" for="customControlValidation2">Publier</label>
                    </div>
                    <div class="custom-control custom-radio mb-3 custom-control-inline">
                        <input type="radio" class="custom-control-input" id="customControlValidation3" name="radio-stacked" required>
                        <label class="custom-control-label" for="customControlValidation3">Brouillon</label>
                        <div class="invalid-feedback">More example invalid feedback text</div>
                    </div>
                </div>
                <div>
                    <a href="#" class="btn btn-primary">Enregistrer</a>
                </div>
            </blockquote>
        </div>
    </div>
</div>