<p class="text-right">Bienvenue, Christophe HAZEBROUCQ</p>
        <h1>Liste des Utilisateurs</h1>
        <div>
            <a href="AddUser.php" class="btn btn-primary mb-4">Ajouter un utilisateur</a>
        </div>
        <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="w-20">Avatar</th>
                    <th scope="col">User name</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">nombre d'article</th>
                    <th class="col">nombre de commentaire</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                    <td scope="col"><a href="#"><img src="img/1.jpg" alt="grlos chat" class="img-thumbnail rounded" data-toggle="modal" data-target="#image1"></a></td>
                        <th scope="row">ChristO</th>
                        <td scope="col">christophe@nom.com</td>
                        <td scope="col">15</td>
                        <td scope="col">2</td>
                        <td scope="col">
                            <a href="#"><i class="fas fa-edit"></i></a>
                            <a href="#"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    <tr>
                    <td scope="col"><a href="#"><img src="img/2.jpg" alt="Zelda de hutt" class="img-thumbnail rounded" data-toggle="modal" data-target="#image2"></a></td>
                        <th scope="row">Ray</th>
                        <td scope="col">ray@mon.com</td>
                        <td scope="col">0</td>
                        <td scope="col">150</td>
                        <td scope="col">
                            <a href="#"><i class="fas fa-edit"></i></a>
                            <a href="#"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                </tbody>
              </table>

              <div class="modal fade" id="image1" tabindex="-1" role="dialog" aria-labelledby="image1" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">image1</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                         <a href="img/1.jpg"><img src="img/1.jpg" alt="grlos chat" class="img-fluid""></a>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <button type="button" class="btn btn-primary">Save changes</button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="modal fade" id="image2" tabindex="-1" role="dialog" aria-labelledby="image2" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">image2</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                             <a href="img/2.jpg"><img src="img/2.jpg" alt="grlos chat" class="img-fluid""></a>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              <button type="button" class="btn btn-primary">Save changes</button>
                            </div>
                          </div>
                        </div>
                      </div>
                

